{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mooseng.serviceAccountName" . }}
  namespace: {{ .Values.namespace | default "mooseng" }}
  labels:
    {{- include "mooseng.labels" . | nindent 4 }}
{{- end -}}