# MooseNG Docker Compose - Unified Demo Setup
# 3 Masters (with Raft consensus), 3 Chunkservers, 3 Clients

services:
  # Master Servers with Raft Consensus
  master-1:
    build:
      context: .
      dockerfile: docker/Dockerfile.master
    container_name: mooseng-master-1
    hostname: master-1
    environment:
      - MOOSENG_NODE_ID=master-1
      - MOOSENG_CLUSTER_ID=mooseng-cluster
      - MOOSENG_RAFT_PEERS=master-1:9422,master-2:9422,master-3:9422
      - MOOSENG_LISTEN_PORT=9421
      - MOOSENG_GRPC_PORT=9422
      - MOOSENG_METRICS_PORT=9423
      - MOOSENG_LOG_LEVEL=info
      - MOOSENG_DATA_DIR=/var/lib/mooseng/master
      - MOOSENG_LOG_DIR=/var/log/mooseng
    ports:
      - "9421:9421"  # Client API
      - "9422:9422"  # Raft
      - "9423:9423"  # Metrics
    volumes:
      - master-1-data:/data
    networks:
      - mooseng-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/usr/local/bin/mooseng-master", "--health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  master-2:
    build:
      context: .
      dockerfile: docker/Dockerfile.master
    container_name: mooseng-master-2
    hostname: master-2
    environment:
      - MOOSENG_NODE_ID=master-2
      - MOOSENG_CLUSTER_ID=mooseng-cluster
      - MOOSENG_RAFT_PEERS=master-1:9422,master-2:9422,master-3:9422
      - MOOSENG_LISTEN_PORT=9421
      - MOOSENG_GRPC_PORT=9422
      - MOOSENG_METRICS_PORT=9423
      - MOOSENG_LOG_LEVEL=info
      - MOOSENG_DATA_DIR=/var/lib/mooseng/master
      - MOOSENG_LOG_DIR=/var/log/mooseng
    ports:
      - "9431:9421"
      - "9432:9422"
      - "9433:9423"
    volumes:
      - master-2-data:/data
    networks:
      - mooseng-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/usr/local/bin/mooseng-master", "--health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  master-3:
    build:
      context: .
      dockerfile: docker/Dockerfile.master
    container_name: mooseng-master-3
    hostname: master-3
    environment:
      - MOOSENG_NODE_ID=master-3
      - MOOSENG_CLUSTER_ID=mooseng-cluster
      - MOOSENG_RAFT_PEERS=master-1:9422,master-2:9422,master-3:9422
      - MOOSENG_LISTEN_PORT=9421
      - MOOSENG_GRPC_PORT=9422
      - MOOSENG_METRICS_PORT=9423
      - MOOSENG_LOG_LEVEL=info
      - MOOSENG_DATA_DIR=/var/lib/mooseng/master
      - MOOSENG_LOG_DIR=/var/log/mooseng
    ports:
      - "9441:9421"
      - "9442:9422"
      - "9443:9423"
    volumes:
      - master-3-data:/data
    networks:
      - mooseng-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/usr/local/bin/mooseng-master", "--health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Chunk Servers
  chunkserver-1:
    build:
      context: .
      dockerfile: docker/Dockerfile.chunkserver
    container_name: mooseng-chunkserver-1
    hostname: chunkserver-1
    environment:
      - MOOSENG_SERVER_ID=chunkserver-1
      - MOOSENG_MASTER_ADDRS=master-1:9421,master-2:9421,master-3:9421
      - MOOSENG_LISTEN_PORT=9420
      - MOOSENG_METRICS_PORT=9425
      - MOOSENG_DATA_DIRS=/data/disk1,/data/disk2,/data/disk3,/data/disk4
      - MOOSENG_LOG_LEVEL=info
      - MOOSENG_LOG_DIR=/var/log/mooseng
    ports:
      - "9420:9420"
      - "9425:9425"
    volumes:
      - chunkserver-1-disk1:/data/disk1
      - chunkserver-1-disk2:/data/disk2
      - chunkserver-1-disk3:/data/disk3
      - chunkserver-1-disk4:/data/disk4
    networks:
      - mooseng-net
    restart: unless-stopped
    depends_on:
      - master-1
      - master-2
      - master-3
    healthcheck:
      test: ["CMD", "/usr/local/bin/mooseng-chunkserver", "--health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  chunkserver-2:
    build:
      context: .
      dockerfile: docker/Dockerfile.chunkserver
    container_name: mooseng-chunkserver-2
    hostname: chunkserver-2
    environment:
      - MOOSENG_SERVER_ID=chunkserver-2
      - MOOSENG_MASTER_ADDRS=master-1:9421,master-2:9421,master-3:9421
      - MOOSENG_LISTEN_PORT=9420
      - MOOSENG_METRICS_PORT=9425
      - MOOSENG_DATA_DIRS=/data/disk1,/data/disk2,/data/disk3,/data/disk4
      - MOOSENG_LOG_LEVEL=info
      - MOOSENG_LOG_DIR=/var/log/mooseng
    ports:
      - "9450:9420"
      - "9455:9425"
    volumes:
      - chunkserver-2-disk1:/data/disk1
      - chunkserver-2-disk2:/data/disk2
      - chunkserver-2-disk3:/data/disk3
      - chunkserver-2-disk4:/data/disk4
    networks:
      - mooseng-net
    restart: unless-stopped
    depends_on:
      - master-1
      - master-2
      - master-3
    healthcheck:
      test: ["CMD", "/usr/local/bin/mooseng-chunkserver", "--health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  chunkserver-3:
    build:
      context: .
      dockerfile: docker/Dockerfile.chunkserver
    container_name: mooseng-chunkserver-3
    hostname: chunkserver-3
    environment:
      - MOOSENG_SERVER_ID=chunkserver-3
      - MOOSENG_MASTER_ADDRS=master-1:9421,master-2:9421,master-3:9421
      - MOOSENG_LISTEN_PORT=9420
      - MOOSENG_METRICS_PORT=9425
      - MOOSENG_DATA_DIRS=/data/disk1,/data/disk2,/data/disk3,/data/disk4
      - MOOSENG_LOG_LEVEL=info
      - MOOSENG_LOG_DIR=/var/log/mooseng
    ports:
      - "9460:9420"
      - "9465:9425"
    volumes:
      - chunkserver-3-disk1:/data/disk1
      - chunkserver-3-disk2:/data/disk2
      - chunkserver-3-disk3:/data/disk3
      - chunkserver-3-disk4:/data/disk4
    networks:
      - mooseng-net
    restart: unless-stopped
    depends_on:
      - master-1
      - master-2
      - master-3
    healthcheck:
      test: ["CMD", "/usr/local/bin/mooseng-chunkserver", "--health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Client Instances
  client-1:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
    container_name: mooseng-client-1
    hostname: client-1
    environment:
      - MOOSENG_MASTER_ENDPOINTS=master-1:9421,master-2:9421,master-3:9421
      - MOOSENG_MASTER_ADDRS=master-1:9421,master-2:9421,master-3:9421
      - MOOSENG_MOUNT_POINT=/mnt/mooseng
      - MOOSENG_LOG_LEVEL=info
      - MOOSENG_LOG_DIR=/var/log/mooseng
      - MOOSENG_CACHE_SIZE_MB=256
    ports:
      - "9427:9427"
    volumes:
      - client-1-cache:/cache
    networks:
      - mooseng-net
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/fuse:/dev/fuse
    depends_on:
      - master-1
      - master-2
      - master-3
      - chunkserver-1
      - chunkserver-2
      - chunkserver-3

  client-2:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
    container_name: mooseng-client-2
    hostname: client-2
    environment:
      - MOOSENG_MASTER_ENDPOINTS=master-1:9421,master-2:9421,master-3:9421
      - MOOSENG_MASTER_ADDRS=master-1:9421,master-2:9421,master-3:9421
      - MOOSENG_MOUNT_POINT=/mnt/mooseng
      - MOOSENG_LOG_LEVEL=info
      - MOOSENG_LOG_DIR=/var/log/mooseng
      - MOOSENG_CACHE_SIZE_MB=256
    ports:
      - "9437:9427"
    volumes:
      - client-2-cache:/cache
    networks:
      - mooseng-net
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/fuse:/dev/fuse
    depends_on:
      - master-1
      - master-2
      - master-3
      - chunkserver-1
      - chunkserver-2
      - chunkserver-3

  client-3:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
    container_name: mooseng-client-3
    hostname: client-3
    environment:
      - MOOSENG_MASTER_ENDPOINTS=master-1:9421,master-2:9421,master-3:9421
      - MOOSENG_MASTER_ADDRS=master-1:9421,master-2:9421,master-3:9421
      - MOOSENG_MOUNT_POINT=/mnt/mooseng
      - MOOSENG_LOG_LEVEL=info
      - MOOSENG_LOG_DIR=/var/log/mooseng
      - MOOSENG_CACHE_SIZE_MB=256
    ports:
      - "9447:9427"
    volumes:
      - client-3-cache:/cache
    networks:
      - mooseng-net
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/fuse:/dev/fuse
    depends_on:
      - master-1
      - master-2
      - master-3
      - chunkserver-1
      - chunkserver-2
      - chunkserver-3

  # Monitoring Stack
  prometheus:
    image: prom/prometheus:v2.47.0
    container_name: mooseng-prometheus
    hostname: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    networks:
      - mooseng-net
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.1.0
    container_name: mooseng-grafana
    hostname: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - grafana-data:/var/lib/grafana
      - ./docker/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./docker/grafana/datasources:/etc/grafana/provisioning/datasources:ro
    networks:
      - mooseng-net
    restart: unless-stopped
    depends_on:
      - prometheus

  # Web Dashboard
  dashboard:
    image: nginx:alpine
    container_name: mooseng-dashboard
    hostname: dashboard
    ports:
      - "8080:80"
    volumes:
      - ./dashboard:/usr/share/nginx/html:ro
    networks:
      - mooseng-net
    restart: unless-stopped

networks:
  mooseng-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

volumes:
  # Master volumes
  master-1-data:
  master-2-data:
  master-3-data:
  
  # Chunkserver volumes (4 disks each)
  chunkserver-1-disk1:
  chunkserver-1-disk2:
  chunkserver-1-disk3:
  chunkserver-1-disk4:
  chunkserver-2-disk1:
  chunkserver-2-disk2:
  chunkserver-2-disk3:
  chunkserver-2-disk4:
  chunkserver-3-disk1:
  chunkserver-3-disk2:
  chunkserver-3-disk3:
  chunkserver-3-disk4:
  
  # Client cache volumes
  client-1-cache:
  client-2-cache:
  client-3-cache:
  
  # Monitoring volumes
  prometheus-data:
  grafana-data: