version: '3.8'

services:
  # Master servers with mock implementation
  master-1:
    build:
      context: .
      dockerfile: docker/Dockerfile.mock-master
    container_name: mooseng-master-1
    hostname: master-1
    environment:
      - MOOSENG_NODE_ID=1
      - MOOSENG_CLUSTER_NAME=mooseng-demo
      - MOOSENG_CLIENT_PORT=9421
    ports:
      - "9421:9421"  # Client API
      - "9424:9424"  # Metrics (simulated on same service)
    networks:
      - mooseng-net
    restart: unless-stopped

  master-2:
    build:
      context: .
      dockerfile: docker/Dockerfile.mock-master
    container_name: mooseng-master-2
    hostname: master-2
    environment:
      - MOOSENG_NODE_ID=2
      - MOOSENG_CLUSTER_NAME=mooseng-demo
      - MOOSENG_CLIENT_PORT=9421
    ports:
      - "9431:9421"
      - "9434:9424"
    networks:
      - mooseng-net
    restart: unless-stopped

  master-3:
    build:
      context: .
      dockerfile: docker/Dockerfile.mock-master
    container_name: mooseng-master-3
    hostname: master-3
    environment:
      - MOOSENG_NODE_ID=3
      - MOOSENG_CLUSTER_NAME=mooseng-demo
      - MOOSENG_CLIENT_PORT=9421
    ports:
      - "9441:9421"
      - "9444:9424"
    networks:
      - mooseng-net
    restart: unless-stopped

  # Chunk servers with mock implementation
  chunkserver-1:
    build:
      context: .
      dockerfile: docker/Dockerfile.mock-chunkserver
    container_name: mooseng-chunkserver-1
    hostname: chunkserver-1
    environment:
      - MOOSENG_SERVER_ID=1
      - MOOSENG_MASTER_ENDPOINTS=master-1:9422,master-2:9422,master-3:9422
      - MOOSENG_PORT=9420
    ports:
      - "9420:9420"
      - "9425:9425"
    volumes:
      - chunkserver-1-data1:/data1
      - chunkserver-1-data2:/data2
      - chunkserver-1-data3:/data3
      - chunkserver-1-data4:/data4
    networks:
      - mooseng-net
    restart: unless-stopped
    depends_on:
      - master-1

  chunkserver-2:
    build:
      context: .
      dockerfile: docker/Dockerfile.mock-chunkserver
    container_name: mooseng-chunkserver-2
    hostname: chunkserver-2
    environment:
      - MOOSENG_SERVER_ID=2
      - MOOSENG_MASTER_ENDPOINTS=master-1:9422,master-2:9422,master-3:9422
      - MOOSENG_PORT=9420
    ports:
      - "9450:9420"
      - "9455:9425"
    volumes:
      - chunkserver-2-data1:/data1
      - chunkserver-2-data2:/data2
      - chunkserver-2-data3:/data3
      - chunkserver-2-data4:/data4
    networks:
      - mooseng-net
    restart: unless-stopped
    depends_on:
      - master-1

  chunkserver-3:
    build:
      context: .
      dockerfile: docker/Dockerfile.mock-chunkserver
    container_name: mooseng-chunkserver-3
    hostname: chunkserver-3
    environment:
      - MOOSENG_SERVER_ID=3
      - MOOSENG_MASTER_ENDPOINTS=master-1:9422,master-2:9422,master-3:9422
      - MOOSENG_PORT=9420
    ports:
      - "9460:9420"
      - "9465:9425"
    volumes:
      - chunkserver-3-data1:/data1
      - chunkserver-3-data2:/data2
      - chunkserver-3-data3:/data3
      - chunkserver-3-data4:/data4
    networks:
      - mooseng-net
    restart: unless-stopped
    depends_on:
      - master-1

  # Metalogger for metadata backup
  metalogger-1:
    build:
      context: .
      dockerfile: docker/Dockerfile.metalogger
      args:
        RUST_VERSION: "1.79"
    container_name: mooseng-metalogger-1
    hostname: metalogger-1
    environment:
      - RUST_LOG=info
      - MOOSENG_BIND_ADDRESS=0.0.0.0
      - MOOSENG_PORT=9419
      - MOOSENG_METRICS_PORT=9426
      - MOOSENG_HEALTH_PORT=9428
      - MOOSENG_MASTER_ENDPOINTS=master-1:9422,master-2:9422,master-3:9422
      - MOOSENG_DOWNLOAD_FREQ_SECONDS=3600
      - MOOSENG_MAX_BACKUP_FILES=7
      - MOOSENG_ENABLE_COMPRESSION=true
      - MOOSENG_ENABLE_HEALTH_CHECKS=true
    ports:
      - "9419:9419"
      - "9426:9426"
      - "9428:9428"
    volumes:
      - metalogger-1-data:/var/lib/mooseng/metalogger
      - metalogger-1-logs:/var/log/mooseng
      - ./docker/configs:/etc/mooseng/configs:ro
    networks:
      - mooseng-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/usr/local/bin/mooseng-metalogger", "--health-check"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Client instances with mock implementation
  client-1:
    build:
      context: .
      dockerfile: docker/Dockerfile.mock-client
    container_name: mooseng-client-1
    hostname: client-1
    environment:
      - MOOSENG_CLIENT_ID=client-1
      - MOOSENG_MASTER_ENDPOINTS=master-1:9421,master-2:9421,master-3:9421
      - MOOSENG_METRICS_PORT=9427
    ports:
      - "9427:9427"
    volumes:
      - ./mnt/client-1:/mnt/mooseng:rw
      - client-1-cache:/var/cache/mooseng
    networks:
      - mooseng-net
    restart: unless-stopped
    depends_on:
      - master-1
      - chunkserver-1

  client-2:
    build:
      context: .
      dockerfile: docker/Dockerfile.mock-client
    container_name: mooseng-client-2
    hostname: client-2
    environment:
      - MOOSENG_CLIENT_ID=client-2
      - MOOSENG_MASTER_ENDPOINTS=master-1:9421,master-2:9421,master-3:9421
      - MOOSENG_METRICS_PORT=9427
    ports:
      - "9437:9427"
    volumes:
      - ./mnt/client-2:/mnt/mooseng:rw
      - client-2-cache:/var/cache/mooseng
    networks:
      - mooseng-net
    restart: unless-stopped
    depends_on:
      - master-1
      - chunkserver-1

  client-3:
    build:
      context: .
      dockerfile: docker/Dockerfile.mock-client
    container_name: mooseng-client-3
    hostname: client-3
    environment:
      - MOOSENG_CLIENT_ID=client-3
      - MOOSENG_MASTER_ENDPOINTS=master-1:9421,master-2:9421,master-3:9421
      - MOOSENG_METRICS_PORT=9427
    ports:
      - "9447:9427"
    volumes:
      - ./mnt/client-3:/mnt/mooseng:rw
      - client-3-cache:/var/cache/mooseng
    networks:
      - mooseng-net
    restart: unless-stopped
    depends_on:
      - master-1
      - chunkserver-1

  # CLI container for management
  cli:
    image: curlimages/curl:latest
    container_name: mooseng-cli
    hostname: cli
    networks:
      - mooseng-net
    volumes:
      - ./scripts:/scripts:ro
    depends_on:
      - master-1
    stdin_open: true
    tty: true
    entrypoint: ["/bin/sh"]
    command: ["-c", "echo 'MooseNG CLI ready. Use curl to interact with services.' && sh"]

  # Web Dashboard
  dashboard:
    image: nginx:alpine
    container_name: mooseng-dashboard
    hostname: dashboard
    ports:
      - "8080:80"
    volumes:
      - ./unified_dashboard/public:/usr/share/nginx/html:ro
      - ./unified_dashboard/assets:/usr/share/nginx/html/assets:ro
      - ./unified_dashboard/components:/usr/share/nginx/html/components:ro
      - ./unified_dashboard/src:/usr/share/nginx/html/src:ro
    networks:
      - mooseng-net
    restart: unless-stopped

  # Prometheus for metrics
  prometheus:
    image: prom/prometheus:v2.47.0
    container_name: mooseng-prometheus
    hostname: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    networks:
      - mooseng-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s

  # Grafana for visualization
  grafana:
    image: grafana/grafana:10.1.0
    container_name: mooseng-grafana
    hostname: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - grafana-data:/var/lib/grafana
      - ./docker/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./docker/grafana/datasources:/etc/grafana/provisioning/datasources:ro
    networks:
      - mooseng-net
    restart: unless-stopped
    depends_on:
      prometheus:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s

networks:
  mooseng-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

volumes:
  # Chunk server data volumes
  chunkserver-1-data1:
  chunkserver-1-data2:
  chunkserver-1-data3:
  chunkserver-1-data4:
  chunkserver-1-logs:
  chunkserver-2-data1:
  chunkserver-2-data2:
  chunkserver-2-data3:
  chunkserver-2-data4:
  chunkserver-2-logs:
  chunkserver-3-data1:
  chunkserver-3-data2:
  chunkserver-3-data3:
  chunkserver-3-data4:
  chunkserver-3-logs:
  
  # Metalogger volumes
  metalogger-1-data:
  metalogger-1-logs:
  
  # Client cache volumes
  client-1-cache:
  client-2-cache:
  client-3-cache:
  
  # Monitoring volumes
  prometheus-data:
  grafana-data: