version: '3.8'

services:
  # Master servers (HA configuration)
  master-1:
    build:
      context: .
      dockerfile: docker/Dockerfile.master
    container_name: mooseng-master-1
    hostname: master-1
    environment:
      - RUST_LOG=info
      - MOOSENG_NODE_ID=1
      - MOOSENG_CLUSTER_NAME=mooseng-dev
      - MOOSENG_RAFT_PEERS=master-1:9423,master-2:9423,master-3:9423
      - MOOSENG_BIND_ADDRESS=0.0.0.0
      - MOOSENG_CLIENT_PORT=9421
      - MOOSENG_CHUNKSERVER_PORT=9422
      - MOOSENG_RAFT_PORT=9423
    ports:
      - "9421:9421"  # Client port
      - "9422:9422"  # Chunkserver port
      - "9423:9423"  # Raft port
    volumes:
      - master-1-data:/var/lib/mooseng/master
      - master-1-logs:/var/log/mooseng
      - ./docker/configs:/etc/mooseng/configs:ro
    networks:
      - mooseng-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/usr/local/bin/mooseng-master", "--health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  master-2:
    build:
      context: .
      dockerfile: docker/Dockerfile.master
    container_name: mooseng-master-2
    hostname: master-2
    environment:
      - RUST_LOG=info
      - MOOSENG_NODE_ID=2
      - MOOSENG_CLUSTER_NAME=mooseng-dev
      - MOOSENG_RAFT_PEERS=master-1:9423,master-2:9423,master-3:9423
      - MOOSENG_BIND_ADDRESS=0.0.0.0
      - MOOSENG_CLIENT_PORT=9421
      - MOOSENG_CHUNKSERVER_PORT=9422
      - MOOSENG_RAFT_PORT=9423
    ports:
      - "9431:9421"  # Client port
      - "9432:9422"  # Chunkserver port
      - "9433:9423"  # Raft port
    volumes:
      - master-2-data:/var/lib/mooseng/master
      - master-2-logs:/var/log/mooseng
      - ./docker/configs:/etc/mooseng/configs:ro
    networks:
      - mooseng-net
    restart: unless-stopped
    depends_on:
      - master-1
    healthcheck:
      test: ["CMD", "/usr/local/bin/mooseng-master", "--health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  master-3:
    build:
      context: .
      dockerfile: docker/Dockerfile.master
    container_name: mooseng-master-3
    hostname: master-3
    environment:
      - RUST_LOG=info
      - MOOSENG_NODE_ID=3
      - MOOSENG_CLUSTER_NAME=mooseng-dev
      - MOOSENG_RAFT_PEERS=master-1:9423,master-2:9423,master-3:9423
      - MOOSENG_BIND_ADDRESS=0.0.0.0
      - MOOSENG_CLIENT_PORT=9421
      - MOOSENG_CHUNKSERVER_PORT=9422
      - MOOSENG_RAFT_PORT=9423
    ports:
      - "9441:9421"  # Client port
      - "9442:9422"  # Chunkserver port
      - "9443:9423"  # Raft port
    volumes:
      - master-3-data:/var/lib/mooseng/master
      - master-3-logs:/var/log/mooseng
      - ./docker/configs:/etc/mooseng/configs:ro
    networks:
      - mooseng-net
    restart: unless-stopped
    depends_on:
      - master-1
      - master-2
    healthcheck:
      test: ["CMD", "/usr/local/bin/mooseng-master", "--health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  # Chunk servers
  chunkserver-1:
    build:
      context: .
      dockerfile: docker/Dockerfile.chunkserver
    container_name: mooseng-chunkserver-1
    hostname: chunkserver-1
    environment:
      - RUST_LOG=info
      - MOOSENG_MASTER_ENDPOINTS=master-1:9422,master-2:9422,master-3:9422
      - MOOSENG_BIND_ADDRESS=0.0.0.0
      - MOOSENG_PORT=9420
      - MOOSENG_DATA_DIRS=/data1,/data2
      - MOOSENG_CHUNK_SIZE_MB=64
    ports:
      - "9420:9420"
    volumes:
      - chunkserver-1-data1:/data1
      - chunkserver-1-data2:/data2
      - chunkserver-1-logs:/var/log/mooseng
      - ./docker/configs:/etc/mooseng/configs:ro
    networks:
      - mooseng-net
    restart: unless-stopped
    depends_on:
      - master-1
    healthcheck:
      test: ["CMD", "/usr/local/bin/mooseng-chunkserver", "--health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  chunkserver-2:
    build:
      context: .
      dockerfile: docker/Dockerfile.chunkserver
    container_name: mooseng-chunkserver-2
    hostname: chunkserver-2
    environment:
      - RUST_LOG=info
      - MOOSENG_MASTER_ENDPOINTS=master-1:9422,master-2:9422,master-3:9422
      - MOOSENG_BIND_ADDRESS=0.0.0.0
      - MOOSENG_PORT=9420
      - MOOSENG_DATA_DIRS=/data1,/data2
      - MOOSENG_CHUNK_SIZE_MB=64
    ports:
      - "9450:9420"
    volumes:
      - chunkserver-2-data1:/data1
      - chunkserver-2-data2:/data2
      - chunkserver-2-logs:/var/log/mooseng
      - ./docker/configs:/etc/mooseng/configs:ro
    networks:
      - mooseng-net
    restart: unless-stopped
    depends_on:
      - master-1
    healthcheck:
      test: ["CMD", "/usr/local/bin/mooseng-chunkserver", "--health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  chunkserver-3:
    build:
      context: .
      dockerfile: docker/Dockerfile.chunkserver
    container_name: mooseng-chunkserver-3
    hostname: chunkserver-3
    environment:
      - RUST_LOG=info
      - MOOSENG_MASTER_ENDPOINTS=master-1:9422,master-2:9422,master-3:9422
      - MOOSENG_BIND_ADDRESS=0.0.0.0
      - MOOSENG_PORT=9420
      - MOOSENG_DATA_DIRS=/data1,/data2
      - MOOSENG_CHUNK_SIZE_MB=64
    ports:
      - "9460:9420"
    volumes:
      - chunkserver-3-data1:/data1
      - chunkserver-3-data2:/data2
      - chunkserver-3-logs:/var/log/mooseng
      - ./docker/configs:/etc/mooseng/configs:ro
    networks:
      - mooseng-net
    restart: unless-stopped
    depends_on:
      - master-1
    healthcheck:
      test: ["CMD", "/usr/local/bin/mooseng-chunkserver", "--health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  # Metalogger for backup
  metalogger-1:
    build:
      context: .
      dockerfile: docker/Dockerfile.metalogger
    container_name: mooseng-metalogger-1
    hostname: metalogger-1
    environment:
      - RUST_LOG=info
      - MOOSENG_MASTER_ENDPOINTS=master-1:9422,master-2:9422,master-3:9422
      - MOOSENG_BIND_ADDRESS=0.0.0.0
      - MOOSENG_PORT=9419
      - MOOSENG_DOWNLOAD_FREQ_SECONDS=3600
    ports:
      - "9419:9419"
    volumes:
      - metalogger-1-data:/var/lib/mooseng/metalogger
      - metalogger-1-logs:/var/log/mooseng
      - ./docker/configs:/etc/mooseng/configs:ro
    networks:
      - mooseng-net
    restart: unless-stopped
    depends_on:
      - master-1
    healthcheck:
      test: ["CMD", "/usr/local/bin/mooseng-metalogger", "--health-check"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Client example (FUSE mount)
  client-example:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
    container_name: mooseng-client-example
    hostname: client-example
    environment:
      - RUST_LOG=info
      - MOOSENG_MASTER_ENDPOINTS=master-1:9421,master-2:9421,master-3:9421
      - MOOSENG_MOUNT_POINT=/mnt/mooseng
      - MOOSENG_CACHE_SIZE_MB=512
    volumes:
      - ./mnt:/mnt/mooseng:shared
      - client-logs:/var/log/mooseng
      - ./docker/configs:/etc/mooseng/configs:ro
    networks:
      - mooseng-net
    restart: unless-stopped
    depends_on:
      - master-1
      - chunkserver-1
      - chunkserver-2
      - chunkserver-3
    privileged: true  # Required for FUSE mounting
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN

  # CLI/Admin container for management
  cli:
    build:
      context: .
      dockerfile: docker/Dockerfile.cli
    container_name: mooseng-cli
    hostname: cli
    environment:
      - RUST_LOG=info
      - MOOSENG_MASTER_ENDPOINTS=master-1:9421,master-2:9421,master-3:9421
    volumes:
      - cli-home:/home/mooseng
      - ./docker/configs:/etc/mooseng/configs:ro
    networks:
      - mooseng-net
    depends_on:
      - master-1
    stdin_open: true
    tty: true
    command: ["/bin/sh"]

  # Monitoring with Prometheus
  prometheus:
    image: prom/prometheus:v2.47.0
    container_name: mooseng-prometheus
    hostname: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
    networks:
      - mooseng-net
    restart: unless-stopped

  # Grafana for visualization
  grafana:
    image: grafana/grafana:10.1.0
    container_name: mooseng-grafana
    hostname: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - grafana-data:/var/lib/grafana
      - ./docker/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./docker/grafana/datasources:/etc/grafana/provisioning/datasources:ro
    networks:
      - mooseng-net
    restart: unless-stopped
    depends_on:
      - prometheus

networks:
  mooseng-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  # Master server data
  master-1-data:
    driver: local
  master-1-logs:
    driver: local
  master-2-data:
    driver: local
  master-2-logs:
    driver: local
  master-3-data:
    driver: local
  master-3-logs:
    driver: local

  # Chunk server data
  chunkserver-1-data1:
    driver: local
  chunkserver-1-data2:
    driver: local
  chunkserver-1-logs:
    driver: local
  chunkserver-2-data1:
    driver: local
  chunkserver-2-data2:
    driver: local
  chunkserver-2-logs:
    driver: local
  chunkserver-3-data1:
    driver: local
  chunkserver-3-data2:
    driver: local
  chunkserver-3-logs:
    driver: local

  # Metalogger data
  metalogger-1-data:
    driver: local
  metalogger-1-logs:
    driver: local

  # Client and CLI
  client-logs:
    driver: local
  cli-home:
    driver: local

  # Monitoring
  prometheus-data:
    driver: local
  grafana-data:
    driver: local