# Simple Makefile for MooseFS HA module

all:
	@echo "Building HA module as part of mfsmaster"

install:
	@echo "HA module installed as part of mfsmaster"

clean:
	@echo "Cleaning HA module"

distclean: clean
	-rm -f Makefile.in