# Default values for mooseng
# This is a YAML-formatted file.

# Global configuration
global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: ""

# Common configuration
nameOverride: ""
fullnameOverride: ""
namespace: "mooseng"
createNamespace: true

# Service account configuration
serviceAccount:
  create: true
  name: ""

# RBAC configuration
rbac:
  create: true

# Cluster configuration
cluster:
  name: "mooseng"
  replicationFactor: 3
  chunkSizeMB: 64

# Master server configuration
master:
  enabled: true
  replicaCount: 3
  
  image:
    repository: mooseng/master
    tag: "latest"
    pullPolicy: IfNotPresent
  
  ports:
    server: 9421
    raft: 9422
    metrics: 9423
  
  service:
    type: ClusterIP
    annotations: {}
    loadBalancer:
      enabled: false
  
  persistence:
    enabled: true
    storageClass: "fast-ssd"
    size: 10Gi
    accessModes:
      - ReadWriteOnce
  
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
  
  nodeSelector: {}
  tolerations: []
  affinity: {}
  
  podAnnotations: {}
  
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    capabilities:
      drop:
      - ALL
  
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3
  
  extraEnv: []
  extraVolumes: []
  extraVolumeMounts: []
  
  config:
    server:
      listenAddr: "0.0.0.0"
      workers: 8
    data:
      dataDir: "/var/lib/mooseng/master"
      metadataBackupInterval: 300
      metadataChecksum: true
    raft:
      clusterId: "mooseng-k8s"
      electionTimeoutMs: 5000
      heartbeatIntervalMs: 1000
      logCompactionThreshold: 10000
    cache:
      enable: true
      sizeMb: 1024
      ttlSeconds: 300
      hotThreshold: 5
    logging:
      level: "info"
      logDir: "/var/log/mooseng"
      fileRotation: true
      maxFileSizeMb: 100
      maxFiles: 10
    monitoring:
      metricsEnabled: true
      healthCheckInterval: 30
      prometheusMetrics: true
    storageClasses:
      - id: 1
        name: "default"
        copies: 2
        tier: "standard"
      - id: 2
        name: "archive"
        copies: 1
        erasureScheme: "8+4"
        tier: "cold"

# Chunk server configuration
chunkserver:
  enabled: true
  deploymentType: "daemonset"  # or "deployment"
  
  image:
    repository: mooseng/chunkserver
    tag: "latest"
    pullPolicy: IfNotPresent
  
  ports:
    server: 9420
  
  service:
    type: ClusterIP
    annotations: {}
  
  # For DaemonSet deployment
  nodeSelector:
    mooseng.io/chunkserver: "true"
  
  tolerations:
    - key: "mooseng.io/chunkserver"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  
  # For Deployment-based chunkservers
  replicaCount: 3
  
  persistence:
    hostPath:
      enabled: true
      basePath: "/var/lib/mooseng/chunks"
      logsPath: "/var/log/mooseng/chunkserver"
  
  resources:
    requests:
      memory: "2Gi"
      cpu: "1000m"
    limits:
      memory: "4Gi"
      cpu: "2000m"
  
  affinity: {}
  
  podAnnotations: {}
  
  podSecurityContext:
    fsGroup: 1000
  
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
      - ALL
  
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 3
  
  readinessProbe:
    initialDelaySeconds: 15
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  
  terminationGracePeriodSeconds: 60
  dnsPolicy: ClusterFirst
  
  hostInfo:
    enabled: true
    path: "/"
  
  extraEnv: []
  extraVolumes: []
  extraVolumeMounts: []
  
  rbac:
    rules:
    - apiGroups: [""]
      resources: ["pods", "nodes"]
      verbs: ["get", "list", "watch"]
  
  config:
    server:
      bindAddress: "0.0.0.0"
    storage:
      dataDirs:
        - "/data1"
        - "/data2"
      chunkSizeMb: 64
    logging:
      level: "info"
      logDir: "/var/log/mooseng"

# Metalogger configuration
metalogger:
  enabled: true
  replicaCount: 1
  
  image:
    registry: ""
    repository: mooseng/metalogger
    tag: "latest"
    pullPolicy: IfNotPresent
  
  service:
    type: ClusterIP
    port: 9419
    annotations: {}
  
  persistence:
    enabled: true
    storageClass: "standard"
    dataSize: 20Gi
    logsSize: 5Gi
    accessMode: ReadWriteOnce
  
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  
  nodeSelector: {}
  tolerations: []
  affinity: {}
  
  podSecurityContext:
    fsGroup: 1000
  
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
      - ALL
  
  config:
    logLevel: "info"
    downloadFreqSeconds: 3600
    backupLogs: 50

# Client configuration
client:
  enabled: false
  replicaCount: 1
  
  image:
    registry: ""
    repository: mooseng/client
    tag: "latest"
    pullPolicy: IfNotPresent
  
  mountPoint: "/mnt/mooseng"
  
  persistence:
    enabled: true
    storageClass: "standard"
    logsSize: 5Gi
  
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
  
  nodeSelector: {}
  tolerations: []
  affinity: {}
  
  # FUSE requires privileged mode
  securityContext:
    privileged: true
  
  config:
    logLevel: "info"
    cache:
      metadataCacheMB: 256
      dataCacheMB: 1024
      cacheTimeoutSeconds: 300
      prefetchEnabled: true
    io:
      readAheadKB: 1024
      writeCacheMB: 256
      maxConcurrentReads: 16
      maxConcurrentWrites: 8
      timeoutSeconds: 30

# CLI tools
cli:
  enabled: true
  
  image:
    registry: ""
    repository: mooseng/cli
    tag: "latest"
    pullPolicy: IfNotPresent
  
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"

# Monitoring configuration
monitoring:
  enabled: false
  
  prometheus:
    enabled: false
    port: 9090
    retention: "30d"
    storageSize: "10Gi"
  
  grafana:
    enabled: false
    port: 3000
    adminPassword: "admin"
    persistence:
      enabled: true
      size: "1Gi"

# Network policies
networkPolicy:
  enabled: false
  ingress: []
  egress: []

# Pod disruption budgets
podDisruptionBudget:
  master:
    enabled: true
    minAvailable: 2
  chunkserver:
    enabled: true
    maxUnavailable: 1
  metalogger:
    enabled: false

# Service mesh integration
serviceMesh:
  enabled: false
  istio:
    enabled: false

# Backup configuration
backup:
  enabled: false
  schedule: "0 2 * * *"
  retention: "30d"
  storage:
    type: "s3"
    config: {}

# Upgrade strategy
upgradeStrategy:
  type: "RollingUpdate"
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1