apiVersion: v1
kind: Service
metadata:
  name: mooseng-master
  namespace: mooseng
  labels:
    app.kubernetes.io/name: mooseng-master
    app.kubernetes.io/component: master
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: mooseng-master
    app.kubernetes.io/component: master
  ports:
  - name: server
    port: 9421
    protocol: TCP
  - name: raft
    port: 9422
    protocol: TCP
  - name: metrics
    port: 9423
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mooseng-master-lb
  namespace: mooseng
  labels:
    app.kubernetes.io/name: mooseng-master
    app.kubernetes.io/component: master-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: mooseng-master
    app.kubernetes.io/component: master
  ports:
  - name: server
    port: 9421
    targetPort: 9421
    protocol: TCP
  - name: metrics
    port: 9423
    targetPort: 9423
    protocol: TCP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mooseng-master-config
  namespace: mooseng
  labels:
    app.kubernetes.io/name: mooseng-master
    app.kubernetes.io/component: config
data:
  master.toml: |
    [server]
    listen_addr = "0.0.0.0"
    listen_port = 9421
    grpc_port = 9422
    metrics_port = 9423
    workers = 8

    [data]
    data_dir = "/var/lib/mooseng/master"
    metadata_backup_interval = 300
    metadata_checksum = true

    [raft]
    node_id = "${MOOSENG_NODE_ID}"
    cluster_id = "mooseng-k8s"
    peers = "mooseng-master-0.mooseng-master.mooseng.svc.cluster.local:9422,mooseng-master-1.mooseng-master.mooseng.svc.cluster.local:9422,mooseng-master-2.mooseng-master.mooseng.svc.cluster.local:9422"
    election_timeout_ms = 5000
    heartbeat_interval_ms = 1000
    log_compaction_threshold = 10000

    [cache]
    enable = true
    size_mb = 1024
    ttl_seconds = 300
    hot_threshold = 5

    [logging]
    level = "info"
    log_dir = "/var/log/mooseng"
    file_rotation = true
    max_file_size_mb = 100
    max_files = 10

    [monitoring]
    metrics_enabled = true
    health_check_interval = 30
    prometheus_metrics = true

    [storage_classes]
    [[storage_classes.class]]
    id = 1
    name = "default"
    copies = 2
    tier = "standard"

    [[storage_classes.class]]
    id = 2
    name = "archive"
    copies = 1
    erasure_scheme = "8+4"
    tier = "cold"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mooseng-master
  namespace: mooseng
  labels:
    app.kubernetes.io/name: mooseng-master
    app.kubernetes.io/component: master
spec:
  serviceName: mooseng-master
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: mooseng-master
      app.kubernetes.io/component: master
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mooseng-master
        app.kubernetes.io/component: master
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9423"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: mooseng
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
      - name: config-setup
        image: busybox:1.36
        command:
        - sh
        - -c
        - |
          export MOOSENG_NODE_ID="master-${HOSTNAME##*-}"
          envsubst < /etc/mooseng/master.toml > /shared/master.toml
          cat /shared/master.toml
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: config
          mountPath: /etc/mooseng
        - name: shared-config
          mountPath: /shared
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
      containers:
      - name: master
        image: mooseng/master:latest
        imagePullPolicy: IfNotPresent
        command:
        - /usr/local/bin/mooseng-master
        - --config
        - /shared/master.toml
        env:
        - name: RUST_LOG
          value: "info"
        - name: MOOSENG_NODE_ID
          value: "master-$(HOSTNAME##*-)"
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - name: server
          containerPort: 9421
          protocol: TCP
        - name: raft
          containerPort: 9422
          protocol: TCP
        - name: metrics
          containerPort: 9423
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 9423
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 9423
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        volumeMounts:
        - name: data
          mountPath: /var/lib/mooseng/master
        - name: logs
          mountPath: /var/log/mooseng
        - name: shared-config
          mountPath: /shared
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      volumes:
      - name: config
        configMap:
          name: mooseng-master-config
      - name: shared-config
        emptyDir: {}
      - name: logs
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app.kubernetes.io/name: mooseng-master
        app.kubernetes.io/component: master-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: fast-ssd
      resources:
        requests:
          storage: 10Gi