apiVersion: v1
kind: Namespace
metadata:
  name: mooseng
  labels:
    name: mooseng
    app.kubernetes.io/name: mooseng
    app.kubernetes.io/part-of: mooseng
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mooseng
  namespace: mooseng
  labels:
    app.kubernetes.io/name: mooseng
    app.kubernetes.io/component: serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mooseng
  labels:
    app.kubernetes.io/name: mooseng
    app.kubernetes.io/component: rbac
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["statefulsets", "deployments"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mooseng
  labels:
    app.kubernetes.io/name: mooseng
    app.kubernetes.io/component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mooseng
subjects:
- kind: ServiceAccount
  name: mooseng
  namespace: mooseng