[benchmark]
warmup_iterations = 5
measurement_iterations = 50
detailed_report = true

[file_sizes]
small = [1024, 4096, 16384, 65536]          # 1KB to 64KB
medium = [1048576, 10485760]                # 1MB to 10MB
large = [104857600, 1073741824]             # 100MB to 1GB

[concurrency]
levels = [1, 5, 10, 25, 50]

[regions]
test_regions = ["region-1", "region-2", "region-3"]
primary_region = "region-1"

[network_simulation]
latency_ms = [10, 50, 100, 200, 500]
packet_loss_percent = [0.0, 0.1, 0.5, 1.0]
bandwidth_mbps = [100, 1000, 10000]

[metadata_operations]
directory_depths = [1, 3, 5, 10]
files_per_directory = [10, 100, 1000]
